repos:

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: "^src/"
    args: ["src", "tests"]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--line-length", "100",
    "--section-default", "THIRDPARTY", "hooks", "tests"
    ]

- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["src", "tests"]
    exclude: "^(src/ansys/templates/pypkg/{{cookiecutter.project_name_slug}}/)"

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    args: ["--match-dir='^(src)'"]
    exclude: "^(src/ansys/templates/pypkg/{{cookiecutter.project_name_slug}}/)|(tests/)"
