repos:

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: "^({{cookiecutter.project_name_slug}}/)"
    args: ["tests", "hooks"]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--section-default", "THIRDPARTY", "src", "tests"
    ]

- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["tests", "hooks"]
    exclude: "^({{cookiecutter.project_name_slug}}/)"

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    args: ["--match-dir='^(hooks)'"]
    exclude: "^({{cookiecutter.project_name_slug}}/)|(tests/)"
