[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
# Check https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#declarative-config
name = "{{ cookiecutter.pkg_name }}"
version = "attr: {{ cookiecutter.version }}"
download_url = "{{ cookiecutter.repository_url }}"
description = "{{ cookiecutter.short_description }}"
readme = "file: README.rst"
license = "file: = LICENSE"
author = "Ansys, Inc."
author_email = "pyansys.support@ansys.com"
maintainer = "PyAnsys developers"
maintainer_email = "pyansys.support@ansys.com"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[options]
install_requires = [
    "importlib-metadata >=4.0",
]
python_requires = ">={{ cookiecutter.requires_python }}"
packages = "include: ansys"
namespace_packages = ["ansys.{{ cookiecutter.product_name_slug }}.{{cookiecutter.library_name_slug }}"]
