name: GitHub CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Test with tox
        run: tox -e py37


  test:
    name: Test baked project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox-gh-actions
        # The following tox command is being executed by tox-gh-actions. Thus,
        # only the tox environment defined for the particular
        # {{ matrix.python-version }} will be the one executed. See the tox.ini
        # file for more information.
        run: tox
      - name: Test baked project
        run: |
          cd output/test_bake_project0/cookies/bake00/pyproduct-library
          python -m pip install poetry==1.2.0a2
          poetry run tox
